# Generated by Django 3.2.5 on 2021-07-18 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'Mobile'), ('L', 'Laptop'), ('H', 'Headphone'), ('T', 'Television')], max_length=2),
        ),
    ]
